all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    netconf_template_os: ios
  children:
    viptela:
      children:
        viptela_control:
          children:
            vmanage_hosts:
              hosts:
                vmanagedev:
                       ansible_host: 192.168.2.9
            vbond_hosts:
              hosts:
                vbonddev:
                       ansible_host: 192.168.2.11
            vsmart_hosts:
              hosts:
                vsmartdev:
                       ansible_host: 192.168.2.12
        viptela_vedge:
          hosts:
            vedge1:
            vedge2:
            vedge-hq:
