viptela:
  system_ip: 1.1.1.3
  transport_ip: 192.168.3.4
  org: "{{ organization_name }}"
  site_id: 100
  vbond:
    remote: 192.168.3.3

vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 192.168.3.4/24
        tunnel_interface: true
        allow_service:
        - all
        enabled: true
#   routes:
#     - prefix: 10.0.0.0/16
#       next_hop:
#         address: 10.0.0.1
#     - prefix: 10.100.0.0/16
#       next_hop:
#         address: 10.0.0.1
#     - prefix: 172.20.0.0/16
#       next_hop:
#         address: 10.0.0.1
